# Generated by Django 2.0.5 on 2020-02-04 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actionType', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='CustomEnums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DomainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalendarBackend.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalendarBackend.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField()),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('visibility', models.CharField(choices=[('OT', 'own tasks'), ('TTCM', 'tasks that concern me'), ('GT', 'group tasks'), ('ST', 'my subsistent tasks'), ('FT', 'my foremen tasks'), ('ALLT', 'all tasks')], max_length=130)),
                ('status', models.CharField(choices=[('CMPL', 'completed'), ('P', 'pending'), ('NS', 'not started'), ('CNCL', 'cancelled')], max_length=130)),
                ('priority', models.CharField(choices=[('HST', 'highest'), ('H', 'high'), ('M', 'medium'), ('L', 'low'), ('R', 'reminder')], max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('assignedTasks', models.ManyToManyField(related_name='userAssignment', to='CalendarBackend.Task')),
                ('foremen', models.ManyToManyField(related_name='_user_foremen_+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='CalendarBackend.Group')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='state',
            name='tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalendarBackend.Task'),
        ),
        migrations.AddField(
            model_name='state',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='assignedTasks',
            field=models.ManyToManyField(related_name='groupAssignment', to='CalendarBackend.Task'),
        ),
        migrations.AddField(
            model_name='domainmodel',
            name='currentState',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CalendarBackend.State'),
        ),
        migrations.AddField(
            model_name='domainmodel',
            name='prevStates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CalendarBackend.State'),
        ),
        migrations.AddField(
            model_name='action',
            name='madeBy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='nextState',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CalendarBackend.State'),
        ),
        migrations.AddField(
            model_name='action',
            name='prevState',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CalendarBackend.State'),
        ),
    ]
