# Generated by Django 2.0.5 on 2020-02-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=130, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
