# Generated by Django 2.0.5 on 2020-02-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='taskname', max_length=130, unique=True),
        ),
        migrations.RemoveField(
            model_name='state',
            name='groups',
        ),
        migrations.AddField(
            model_name='state',
            name='groups',
            field=models.ManyToManyField(related_name='state', to='CalendarBackend.Group'),
        ),
        migrations.RemoveField(
            model_name='state',
            name='tasks',
        ),
        migrations.AddField(
            model_name='state',
            name='tasks',
            field=models.ManyToManyField(related_name='state', to='CalendarBackend.Task'),
        ),
        migrations.RemoveField(
            model_name='state',
            name='users',
        ),
        migrations.AddField(
            model_name='state',
            name='users',
            field=models.ManyToManyField(related_name='state', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='CalendarBackend.Group'),
        ),
    ]
