# Generated by Django 2.0.5 on 2020-02-05 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarBackend', '0002_auto_20200205_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='groups',
            field=models.ManyToManyField(null=True, related_name='state', to='CalendarBackend.Group'),
        ),
        migrations.AlterField(
            model_name='state',
            name='tasks',
            field=models.ManyToManyField(null=True, related_name='state', to='CalendarBackend.Task'),
        ),
        migrations.AlterField(
            model_name='state',
            name='users',
            field=models.ManyToManyField(null=True, related_name='state', to=settings.AUTH_USER_MODEL),
        ),
    ]
