# Generated by Django 2.0.5 on 2020-02-05 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarBackend', '0003_auto_20200205_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='groups',
            field=models.ManyToManyField(related_name='state', to='CalendarBackend.Group'),
        ),
        migrations.AlterField(
            model_name='state',
            name='tasks',
            field=models.ManyToManyField(related_name='state', to='CalendarBackend.Task'),
        ),
        migrations.AlterField(
            model_name='state',
            name='users',
            field=models.ManyToManyField(related_name='state', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
