# Generated by Django 2.0.5 on 2020-02-05 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarBackend', '0004_auto_20200205_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmodel',
            name='actions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CalendarBackend.Action'),
        ),
        migrations.AlterField(
            model_name='domainmodel',
            name='prevStates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='CalendarBackend.State'),
        ),
    ]
